services:
  postgres:
    container_name: forum-psql
    image: 'postgres'
    ports:
      - 127.0.0.1:5432:5432
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "${conn_string}"]
      interval: 1s
      timeout: 5s
      retries: 5
    volumes:
      - forum-psql:/var/lib/postgresql
  app:
    container_name: forum-backend
    image: "forum-backend-cont:latest"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:2000:2000
    restart: on-failure
    depends_on:
      postgres:
          condition: service_healthy
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - forum-backend:/server
volumes:
  forum-psql:
  forum-backend:

      
 